module.exports = {
  totalProductPrice: "//*[contains(@id,'total_product_price')]",
  address1: "//*[@id='address1']",
  city: "//*[@id='city']",
  state: "//*[@id='id_state']",
  postcode: "//*[@id='postcode']",
  country: "//*[@id='id_country']",
  phone: "//*[@id='phone']",
  phone_mobile: "//*[@id='phone_mobile']",
  alias: "//*[@id='alias']",
  submitAddress: "//*[@id='submitAddress']",
  agreeButton: "//*[@id='cgv']",
  processAddress:"//*[@name='processAddress']",
  processCarrier:"//*[@name='processCarrier']",
  checkoutButton: "//*[@class='cart_navigation clearfix']/*[@title='Proceed to checkout']",
};
